// curiosity-data.js
// Auto-updated 2026-04-17 — do not edit manually

var CURIOSITY_DATA = {
  date: "2026-04-17",
  mainArticle: {
    title: "The Antikythera Mechanism",
    subject: "Antikythera Mechanism",
    subtitle: "Two thousand years before the computer age, Greek craftsmen built a machine that could predict the future of the sky.",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Antikythera_Fragment_A_%28Front%29.webp",
    readTime: "7 min",
    content: [
      { type: "paragraph", text: "In the spring of 1900, a group of Greek sponge divers sheltering from a storm near the small island of Antikythera slipped beneath the waves and found the wreck of an ancient Roman-era cargo ship. Among the marble statues and bronze treasures they hauled to the surface was a corroded, barnacle-encrusted lump of bronze the size of a shoebox. Nobody knew what to make of it. For decades it sat in the Athens National Archaeological Museum, largely ignored, while scholars argued about its date and purpose." },
      { type: "heading", text: "A Machine Out of Time" },
      { type: "paragraph", text: "When researchers finally examined the object carefully in the mid-twentieth century, they found that the lump contained at least 30 interlocking bronze gears of extraordinary precision, arranged in a system of extraordinary mechanical ingenuity. Inscriptions on its surface, slowly deciphered, revealed it was designed to track the movements of the Sun, Moon, and five known planets across the zodiac. It could predict solar and lunar eclipses years in advance, and it even accounted for the irregular speed of the Moon in its elliptical orbit — a refinement that would not be fully explained mathematically until Johannes Kepler in the 17th century." },
      { type: "heading", text: "How It Worked" },
      { type: "paragraph", text: "The mechanism was operated by a hand crank on its side, which drove a main gear connected to the entire interlocking system. Turn the crank forward and the dials on the front and back faces advanced, showing the position of celestial bodies, the phase of the Moon, and the progress of the four-year Olympiad cycle. The most remarkable feature was a differential gear — a device thought to be a medieval European invention — used to combine the motions of the Sun and Moon to compute the lunar phase with a single pointer." },
      { type: "heading", text: "Eclipses on Demand" },
      { type: "paragraph", text: "On the back of the device, two large spiral dials tracked eclipse prediction cycles. One followed the 223-month Saros cycle, the astronomical period after which solar and lunar eclipses repeat in the same sequence — a cycle the Babylonians had mapped centuries earlier. The other tracked the 19-year Metonic cycle, which reconciles the solar year with the lunar month. Small index letters on the eclipse prediction dial indicated which eclipses would be visible and whether they involved the Sun or Moon, making the device a portable astronomical almanac of remarkable sophistication." },
      { type: "heading", text: "Who Built It and Why?" },
      { type: "paragraph", text: "The ship that carried the mechanism sank sometime around 60–70 BCE, but the device itself is thought to have been constructed somewhat earlier, possibly around 100–150 BCE. Strong scholarly consensus points to Rhodes as its place of manufacture, and some researchers have linked it to the tradition of the astronomer and mathematician Hipparchus, who worked on Rhodes and was the first to model the Moon's irregular motion mathematically. The philosopher Cicero wrote admiringly of a similar device owned by his friend Posidonius — also a Rhodian — suggesting such instruments, while rare, were not unique." },
      { type: "heading", text: "The Long Silence" },
      { type: "paragraph", text: "What is most astonishing is not the machine itself but the silence that followed it. No comparable geared mechanism survives from antiquity, and nothing approaching its complexity reappears in the historical record until the astronomical clocks of medieval Europe more than a thousand years later. Whether the tradition of its manufacture died with the craftsmen who built it, was lost in the upheavals of the ancient world, or simply remains undiscovered in wrecks yet to be found, is one of the great unanswered questions in the history of technology." },
      { type: "heading", text: "Modern Decipherment" },
      { type: "paragraph", text: "The breakthrough in understanding the mechanism came in 2006, when an international team used high-resolution X-ray tomography to read thousands of previously invisible inscribed characters hidden inside the corroded fragments. The project, called the Antikythera Mechanism Research Project, effectively turned the device inside out digitally, revealing an instruction manual inscribed on its own surface. Further studies in 2021 reconstructed the entire front panel in detail for the first time, showing a system of planetary pointers arranged in a model of the cosmos that placed the Earth at the centre — a beautifully geocentric universe, precisely engineered in bronze." },
      { type: "paragraph", text: "The Antikythera Mechanism forces us to revise what we think we know about the ancient world. It is not merely a curiosity or a lucky survival — it is evidence that the gap between ancient and modern minds was far narrower than we tend to assume. Somewhere in the workshops of Rhodes or Alexandria, craftsmen understood gearing, differential motion, and astronomical cycles well enough to encode the behaviour of the heavens into a portable hand-cranked box. The question it leaves open is deeply unsettling: how much else did they know, and how much has simply not survived?" }
    ]
  },
  personOfTheDay: {
    name: "Hipparchus of Nicaea",
    lifespan: "c. 190–120 BCE",
    category: "Astronomy & Mathematics",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Head_of_Hipparchus_%28cropped%29.jpg",
    bio: "Hipparchus of Nicaea is widely regarded as the greatest observational astronomer of antiquity, a figure whose work shaped the study of the heavens for nearly two millennia. Born in Nicaea in Bithynia (modern-day Iznik, Turkey), he conducted most of his career on the island of Rhodes, where he built an observatory and accumulated a body of astronomical data of extraordinary precision. Almost none of his original writings survive intact, yet his influence pervades the work of every ancient astronomer who came after him, above all Claudius Ptolemy, who drew heavily on Hipparchus's observations and models.\n\nAmong his many achievements, Hipparchus was the first person known to have compiled a systematic star catalogue, recording the positions of roughly 850 stars with unprecedented accuracy. He discovered the precession of the equinoxes — the slow wobble of Earth's axis that causes the apparent positions of stars to shift over centuries — by comparing his observations with those of Babylonian astronomers made 150 years earlier. This discovery alone places him among the most important scientists of the ancient world, since precession would not be fully explained physically until Isaac Newton described gravitation.\n\nHipparchus also created the first known mathematical model of the Moon's motion, recognising that the Moon moves faster at some points in its orbit than others — what we now understand as the consequence of its elliptical path. He calculated the length of the lunar month to within a fraction of a second of the modern value. His work on trigonometry, including what appears to be the first trigonometric table, provided the mathematical tools that made quantitative astronomy possible. Though history has sometimes allowed his name to fade behind those of Ptolemy and Copernicus, Hipparchus was the quiet giant on whose shoulders all of them stood."
  },
  onThisDay: {
    headline: "BAY OF PIGS INVASION ENDS IN DISASTER",
    date: "April 17, 1961",
    summary: "On April 17, 1961, approximately 1,400 CIA-trained Cuban exiles landed at the Bay of Pigs on the southern coast of Cuba in a covert operation sanctioned by the administration of President John F. Kennedy. The invasion, known as Brigade 2506, was intended to trigger a popular uprising against Fidel Castro's revolutionary government, which had come to power in 1959 and was moving rapidly toward close alignment with the Soviet Union. Within 72 hours the operation had collapsed catastrophically: the expected popular uprising never materialised, Cuban air power destroyed supply ships carrying ammunition and communications equipment, and Castro's forces — far better prepared and informed than US planners had assumed — pinned the invaders on the beach.\n\nBy April 19 the surviving members of the brigade had surrendered. Approximately 114 men were killed and more than 1,100 were taken prisoner, to be ransomed back to the United States in December 1962 in exchange for $53 million worth of food and medicine. The debacle was a profound humiliation for the Kennedy administration, coming only three months into the new presidency, and Kennedy publicly accepted full responsibility. Behind the scenes, the failure intensified mutual suspicion between Kennedy and the CIA, contributed to the administration's later reluctance to commit US air support during the Cuban Missile Crisis planning, and hardened Castro's determination to seek deeper Soviet military protection — setting the stage for the missile crisis of October 1962.",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Aerial_photograph_of_Langness_and_the_bay_at_Castletown_13_February_2014_-_geograph.org.uk_-_3847162.jpg"
  }
};
